
export default {

	FEED_RECEIVED: 'FEED_RECEIVED',
	FEED_CREATED: 'FEED_CREATED',
	SELECT_FEED: 'SELECT_FEED',

	RSS_FEED_RECEIVED: 'RSS_FEED_RECEIVED',
	RSS_LINK_SELECTED: 'RSS_LINK_SELECTED',
	RSS_LINK_RESET: 'RSS_LINK_RESET',
	FETCH_RSS_LINK_DATA: 'FETCH_RSS_LINK_DATA',

	LOGIN_USER: 'LOGIN_USER',
	REGISTER_USER: 'REGISTER_USER'

}
